filter:
  excluded_paths:
    - "tests/*"
    - "doc/*"
    - "var/*"
    - "*/Repository/*"
  dependency_paths:
    - "vendor/*"

before_commands:
  - composer install --prefer-source

build:
  nodes:
    my-test:
      environment:
        php:
          version: 8.0
      dependencies:
        before:
          - sudo apt-get install -y libyaml-dev
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=var/phpunit/test-clover.xml
            coverage:
              file: var/phpunit/test-clover.xml
              format: php-clover

tools:
  external_code_coverage: false
  php_code_sniffer: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_sim: true
  php_changetracking: true

  php_cs_fixer:
    enabled: true
    config:
      level: all
    filter:
      excluded_paths:
        - "tests/*"
        - "doc/*"
        - "vendor/*"
        - "var/*"

  php_mess_detector:
    enabled: true
    filter:
      excluded_paths:
        - "tests/*"
        - "doc/*"
        - "vendor/*"
        - "var/*"

  php_pdepend:
    enabled: true
    filter:
      excluded_paths:
        - "tests/*"
        - "doc/*"
        - "vendor/*"
        - "var/*"

  php_cpd:
    enabled: true
    excluded_dirs:
      - "tests/*"
      - "doc/*"
      - "vendor/*"
      - "var/*"

  php_loc:
    enabled: true
    excluded_dirs:
      - "tests/*"
      - "doc/*"
      - "vendor/*"
      - "var/*"